version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ../:/var/www/html/wp-content/plugins/newtify

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
